/* =================================================================
   Best Friend: breed photo registry.
   AUTO-GENERATED by scripts/fetch-breed-photos.mjs.
   Breeds not listed fall back to the emoji ring, so nothing breaks.
   ================================================================= */
(function () {
  "use strict";

  var HAVE = [
    // ---- dogs (50) ----
    "akita",
    "australian-cattle-dog",
    "australian-shepherd",
    "basset-hound",
    "beagle",
    "bernese-mountain-dog",
    "bichon-frise",
    "bloodhound",
    "border-collie",
    "boston-terrier",
    "boxer",
    "bull-terrier",
    "bulldog",
    "cane-corso",
    "cavalier-king-charles-spaniel",
    "chihuahua",
    "cocker-spaniel",
    "dachshund",
    "dalmatian",
    "doberman-pinscher",
    "english-springer-spaniel",
    "french-bulldog",
    "german-shepherd",
    "german-shorthaired-pointer",
    "golden-retriever",
    "great-dane",
    "greyhound",
    "havanese",
    "irish-setter",
    "jack-russell-terrier",
    "labrador-retriever",
    "lhasa-apso",
    "maltese",
    "miniature-schnauzer",
    "newfoundland",
    "papillon",
    "pembroke-welsh-corgi",
    "pomeranian",
    "poodle",
    "rhodesian-ridgeback",
    "rottweiler",
    "saint-bernard",
    "samoyed",
    "shetland-sheepdog",
    "shih-tzu",
    "siberian-husky",
    "vizsla",
    "weimaraner",
    "whippet",
    "yorkshire-terrier",

    // ---- cats (35) ----
    "abyssinian",
    "american-shorthair",
    "balinese",
    "bengal",
    "birman",
    "bombay",
    "british-shorthair",
    "burmese",
    "chartreux",
    "cornish-rex",
    "devon-rex",
    "egyptian-mau",
    "exotic-shorthair",
    "havana-brown",
    "himalayan",
    "japanese-bobtail",
    "korat",
    "maine-coon",
    "manx",
    "norwegian-forest-cat",
    "oriental-shorthair",
    "persian",
    "ragdoll",
    "russian-blue",
    "savannah",
    "scottish-fold",
    "selkirk-rex",
    "siamese",
    "singapura",
    "snowshoe",
    "somali",
    "sphynx",
    "tonkinese",
    "turkish-angora",
    "turkish-van"
  ];

  var set = {};
  HAVE.forEach(function (s) { set[s] = true; });

  window.BF_BREED_IMAGE = function (slug) {
    return set[slug] ? "assets/breeds/" + slug + ".webp" : null;
  };
  window.BF_BREED_IMAGE_COUNT = HAVE.length;
})();
